<?
/*
프로그램명          새봄로(Sb-Road)
제작                   오경택
메일		             clock934@naver.com
이프로그램은 http://www.jobs21.net  에서 제작되었으며 제작자의 협의없이 재판매를 할 수 없다.
*/

//admin_se_tupw.phtml     (환경설정저장)
include("inc_initarray.phtml"); 
if($jsadmincookieval != "$ADMINID$ADMINPASSWORD")die("접근불가! 로그기록완료!");

function Db_Connect($dbname,$id,$password,$host="localhost"){
$mysql_connect = mysql_connect($host,$id,$password) or die(mysql_error($table_connect));
$table_connect  = mysql_select_db($dbname,$mysql_connect) or die(mysql_error($table_connect));
return $table_connect;
}

//--------------------------------------------------------------------------
function Self_Close(){
echo("
<script>
<!--
alert('환경설정완료! 웹브라우저를 재시작 하십시오!');
self.close();
//-->
</script>
");
exit;
}

//툴하단HTML(상호명/연락처등등)큰따옴표제거
//$Asetinfo_tail=ereg_replace('"','',$Asetinfo_tail);

//---------------------------------------------------------------------------
$TC=Db_Connect($dfile[jelse],$dbuser,$dbpass,$HOST);
$QUE="
			UPDATE $table_jelse[setup] 
			SET setcolor_mtitlechar='$Asetcolor_mtitlechar',
				   setcolor_mtitlebg='$Asetcolor_mtitlebg',
				   setcolor_mtitlebg2='$Asetcolor_mtitlebg2',
				   setcolor_ctitle='$Asetcolor_ctitle',
				   setcolor_outline='$Asetcolor_outline',
				   sethtml_shead='$Asethtml_shead',
				   sethtml_stail='$Asethtml_stail',
				   sethtml_rule='$Asethtml_rule',
				   setpos='$Asetpos',
				   setnum_list='$Asetnum_list',
				   setnum_listmem='$Asetnum_listmem',
				   setsize_photowidth='$Asetsize_photowidth',
				   setsize_photoheight='$Asetsize_photoheight',
   				   setinfo_tail='$Asetinfo_tail',
				   sethtml_banner='$Asethtml_banner',
				   setinfo_head='$Asetinfo_head'
				   ";
//echo $QUE;exit;
$RESULT= mysql_query($QUE) or die(mysql_error($TC));
Self_Close();
//echo "<META http-equiv='refresh' content='0;url=$sfile[index]'>";
?>