<?
/*
프로그램명          새봄로(Sb-Road)
제작                   오경택
메일		             clock934@naver.com
이프로그램은 http://www.jobs21.net  에서 제작되었으며 제작자의 협의없이 재판매를 할 수 없다.
*/

//find_hunt.phtml (구직리스트검색)
include("inc_initarray.phtml");
include("html_style.phtml");
include($MAINMENU);
echo("
<html>
<head>
<title>구직등록자검색</title>
<meta http-equiv='content-type' content='text/html; charset=euc-kr'>
<SCRIPT language='JavaScript'>

function speed_submit() {
//------------------------------
if(document.menu.searchstr.value == '')document.menu.searchstr.focus();
if(document.menu.searchstr.value)document.menu.submit();
}

function hunt_submit(tcode_hidden) {
//-------------------------------
document.form.tcode.value = tcode_hidden;
document.form.submit();
}
</SCRIPT>

</head>

<body bgcolor='white' text='black' link='blue' vlink='purple' alink='red'>
<p align='center'><font color=$SETPYO_CHARCOLOR><b>『구직리스트검색』</b></font> <br><br>
<div align=$setpos>
<table border='0' cellpadding='0' cellspacing='0' width='$SET_WIDTH_LIST' height='20' bgcolor='white' bordercolor='white'>
<tr>
<td width='799' height='644'>
<div align=$setpos>
<table border='0' cellpadding='0' cellspacing='1' width='$SET_WIDTH_LIST' bgcolor=$setcolor_outline style='BORDER-BOTTOM: #006490 0px solid; BORDER-LEFT-COLOR: #006490; BORDER-LEFT-WIDTH: 0px; BORDER-RIGHT-COLOR: navy; BORDER-RIGHT-WIDTH: 0px; BORDER-TOP: #006490 0px solid'>
<tr>
<td width='$SET_WIDTH_LIST' valign='top' bgcolor='white'>
<div align=$setpos>
<table border='0' cellpadding='0'  cellspacing='0' width='$SET_WIDTH_LIST' bgcolor='white' bordercolor='white'>
<tr>
<td width='149' height='26'>

<form name='form' method='post' action=$sfile[list_hunt]>
<select name='work_area' class='colorbox'>
                                    <option value='99'>지역선택(전체)</option>
                                    <option value='0'>서울</option>
                                    <option value='1'>경기</option>
                                    <option value='2'>인천</option>
									<option value='3'>강원</option>
                                    <option value='4'>대전</option>
                                    <option value='5'>충남</option>
                                    <option value='6'>충북</option>
                                    <option value='7'>전북</option>
                                    <option value='8'>전남</option>
                                    <option value='9'>광주</option>
                                    <option value='10'>경북</option>
                                    <option value='11'>경남</option>
                                    <option value='12'>대구</option>
                                    <option value='13'>울산</option>
                                    <option value='14'>부산</option>
                                    <option value='15'>제주</option>
                                    <option value='16'>아시아</option>
                                    <option value='17'>아프리카</option>
                                    <option value='18'>중남미</option>
                                    <option value='19'>오세아니아</option>
                                    <option value='20'>유럽</option>
                                    <option value='21'>북미</option>
</select>
</td>
<td width='74' height='26'><p align='right'><font  color='$SETFINDTITLECOLOR'><b>근무형태</b></font></td>
<td width='329' height='26'>
<p align='left'>
<input type='radio' name='work_kind' value='99' checked><font color=$SETPYO_CHARCOLOR>무관</font>&nbsp;&nbsp;&nbsp;&nbsp; 
<input type='radio' name='work_kind' value='1'><font color=$SETPYO_CHARCOLOR>정규직</font> &nbsp;&nbsp;&nbsp; 
<input type='radio' name='work_kind' value='2'><font color=$SETPYO_CHARCOLOR>&nbsp;비정규직</font> &nbsp;&nbsp; 
<input type='radio' name='work_kind' value='3'><font color=$SETPYO_CHARCOLOR>&nbsp;아르바이트</font></td>


<td width='30' height='26'><p align='right'><font color='$SETFINDTITLECOLOR'><b>성별</b></font></td>
<td width='217' height='26'>&nbsp; 
<input type='radio' name='sex' value='99' checked><font color=$SETPYO_CHARCOLOR>무관</font>&nbsp; 
<input type='radio' name='sex' value='1'><font color=$SETPYO_CHARCOLOR>남</font> &nbsp;&nbsp;
<input type='radio' name='sex' value='2'><font color=$SETPYO_CHARCOLOR>여</font></td>
</tr>

<tr>
<td width='149' height='12'><p>&nbsp;</td>
<td width='74' height='12'><p align='right'><font color='$SETFINDTITLECOLOR'><b>경력</b></font></td>
<td width='329' height='12'><p>
<p align='left'>
<input type='radio' name='experience_year' value='99' checked><font color=$SETPYO_CHARCOLOR>무관 </font>&nbsp;&nbsp;&nbsp;
<input type='radio' name='experience_year' value='0'><font color=$SETPYO_CHARCOLOR>신입</font>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<input type='radio' name='experience_year' value='1'><font color=$SETPYO_CHARCOLOR>경력</font></td> 
<td width='30' height='12'><p align='right'><font color='$SETFINDTITLECOLOR'><b>나이</b></font></td>
<td width='217' height='12'><p>&nbsp;&nbsp;
<select name='age' class='colorbox'>
                                    <option value='99'>무관</option>
                                    <option value='20'>20이하</option>
                                    <option value='25'>25이하</option>
                                    <option value='30'>30이하</option>
                                    <option value='35'>35이하</option>
                                    <option value='40'>40이하</option>
                                    <option value='45'>45이하</option>
                                    <option value='50'>50이하</option>
                                    <option value='55'>55이하</option>
                                    <option value='60'>60이하</option>
</select>


<INPUT TYPE='hidden' NAME=tcode>

</td>
</tr>
</table></div>
</td>
</tr>
</table></div>
<br> <br> 
</form>

<FORM  name=menu METHOD=post ACTION=$sfile[search]>
<input type=text name=searchstr size=15>
<input type=button value='빠른(제목만)검색' onClick='speed_submit()'>
<INPUT type=hidden name=searchdb value=gugic_list>
</form>

<div align='center'><table border='0' cellpadding='0' cellspacing='1' width='$SET_WIDTH_LIST' bgcolor=$setcolor_outline style='BORDER-BOTTOM: #006490 0px solid; BORDER-LEFT-COLOR: #006490; BORDER-LEFT-WIDTH: 0px; BORDER-RIGHT-COLOR: navy; BORDER-RIGHT-WIDTH: 0px; BORDER-TOP: #006490 0px solid'>
<font color=$SETPYO_CHARCOLOR>☞해당업종에서만 검색시 위 검색조건 선택 후 아래의 업종제목 클릭</font> 
<tr>
<td width='256' height='235' valign='top' bgcolor='white'>
<div align='center'><table border='0' cellpadding='0' cellspacing='0' width='250' height='20' bgcolor='white' bordercolor='white'>
<tr>
<td width='255' valign='top'>&nbsp;</td>
</tr>

<tr><td width='255' valign='top'><p><font color='$SETFINDTITLECOLOR'><b>[업종별]</b></font></td></tr>

<tr><td width='255' valign='top'><p>&nbsp;</td></tr>

<tr><td width='255' height='15' valign='top'><p><a href='javascript:hunt_submit(0)'><font color=$SETPYO_CHARCOLOR>건설/토목/건축/조경</font></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(1)'><font color=$SETPYO_CHARCOLOR>광고(기획/홍보/영업/제작)</font></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(2)'><font color=$SETPYO_CHARCOLOR>교육/강사/학원</font></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(3)'><font color=$SETPYO_CHARCOLOR>농업/수산업/축산업/광업</font></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(4)'><font color=$SETPYO_CHARCOLOR>기계/자동차/금속</font></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(5)'><font color=$SETPYO_CHARCOLOR>관광/호텔/여행/항공</font><br></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(6)'><font color=$SETPYO_CHARCOLOR>금융기관(은행/금고/증권/보험)</font></a><br></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(7)'><font color=$SETPYO_CHARCOLOR>건강/병원/의약/화장품</font><br></a></td></tr>
<tr><td  valign='top'><p><a href='javascript:hunt_submit(8)'><font color=$SETPYO_CHARCOLOR>공공기관/공사/공공서비스/협회</font></a></td></tr>
<tr><td  valign='top'><p><a href='javascript:hunt_submit(9)'><font color=$SETPYO_CHARCOLOR>방송/언론</font><br></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(10)'><font color=$SETPYO_CHARCOLOR>출판/인쇄/편집</font></a></td></tr>
<tr><td  valign='top'><p><a href='javascript:hunt_submit(11)'><font color=$SETPYO_CHARCOLOR>목재/제지</font></a></td></tr>
<tr><td  valign='top'><p><a href='javascript:hunt_submit(12)'><font color=$SETPYO_CHARCOLOR>유통/운송/음식료</font></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(13)'><font color=$SETPYO_CHARCOLOR>석유/화학/에너지</font><br></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(14)'><font color=$SETPYO_CHARCOLOR>섬유/의류/패션</font></a><br></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(15)'><font color=$SETPYO_CHARCOLOR>전기/전자/컴퓨터</font><br></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(16)'><font color=$SETPYO_CHARCOLOR>용역/기타서비스</font><br></a></td></tr>
<tr><td  valign='top'><p>&nbsp;</td></tr>
<tr><td  valign='top'><p><font color='$SETFINDTITLECOLOR'><b>[기타]</b></font><font color='$SETFINDTITLECOLOR'><br></font></td></tr>
<tr><td  valign='top'><p>&nbsp;</td></tr>
<tr><td  valign='top'><p><a href='javascript:hunt_submit(17)'><font color=$SETPYO_CHARCOLOR>임원</font></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(18)'><font color=$SETPYO_CHARCOLOR>아르바이트</font><br></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(19)'><font color=$SETPYO_CHARCOLOR>병역특례</font><br></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(20)'><font color=$SETPYO_CHARCOLOR>프리랜서</font><br></a></td></tr>
<tr><td  valign='top'><p><a href='javascript:hunt_submit(21)'><font color=$SETPYO_CHARCOLOR>자원봉사</font><br></a></td></tr>
<tr><td  valign='top'><p><a href='javascript:hunt_submit(22)'><font color=$SETPYO_CHARCOLOR>장애인</font></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(23)'><font color=$SETPYO_CHARCOLOR>고령인</font><br></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(24)'><font color=$SETPYO_CHARCOLOR>노무직</font><br></a></td></tr>
<tr><td  valign='top'><p>&nbsp;</td></tr>
</table></div>

<p>&nbsp;</td>
<td width='245' height='235' valign='top' bgcolor='white'>
<div align='center'><table border='0' cellpadding='0' cellspacing='0' width='250' height='20' bgcolor='white' bordercolor='white'>
<tr><td width='245' valign='top'><p>&nbsp;</td></tr>
<tr><td  valign='top'><p><font color='$SETFINDTITLECOLOR'><b>[사무관리직]</b></font></td></tr>
<tr><td  valign='top'><p>&nbsp;</td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(25)'><font color=$SETPYO_CHARCOLOR>경리/회계/재무</font><br></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(26)'><font color=$SETPYO_CHARCOLOR>마케팅/영업(국내)</font></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(27)'><font color=$SETPYO_CHARCOLOR>무역/영업(해외)</font><br></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(28)'><font color=$SETPYO_CHARCOLOR>사무직(기획/총무/인사/자재/구매/비서)</font></a><br></td></tr>
<tr><td  height='14' valign='top'><p>&nbsp;</td></tr>
<tr><td  valign='top'><p><font color='$SETFINDTITLECOLOR'><b>[전문직]</b></font><font color='$SETFINDTITLECOLOR'><br></font></td></tr>
<tr><td  valign='top'><p>&nbsp;</td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(29)'><font color=$SETPYO_CHARCOLOR>법률/특허</font><br></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(30)'><font color=$SETPYO_CHARCOLOR>증권</font></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(31)'><font color=$SETPYO_CHARCOLOR>번역/통역</font><br></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(32)'><font color=$SETPYO_CHARCOLOR>세무/회계</font><br></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(33)'><font color=$SETPYO_CHARCOLOR>공인중개사/부동산</font><br></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(34)'><font color=$SETPYO_CHARCOLOR>통계/수리</font></a><br></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(35)'><font color=$SETPYO_CHARCOLOR>감정평가</font><br></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(36)'><font color=$SETPYO_CHARCOLOR>경매관리</font><br></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(37)'><font color=$SETPYO_CHARCOLOR>경영지도/경영분석</font></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(38)'><font color=$SETPYO_CHARCOLOR>인테리어/실내디자인</font><br></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(39)'><font color=$SETPYO_CHARCOLOR>의상/패션디자인/코디네이터</font><br></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(40)'><font color=$SETPYO_CHARCOLOR>이벤트/레크레이션</font></a><br></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(41)'><font color=$SETPYO_CHARCOLOR>비디오촬영/카메라</font><br></a></td></tr>
<tr><td  valign='top'><p><a href='javascript:hunt_submit(42)'><font color=$SETPYO_CHARCOLOR>미용</a></td></tr>
<tr><td  valign='top'><p><a href='javascript:hunt_submit(43)'><font color=$SETPYO_CHARCOLOR>서적/소설/시/만화/작가</font><br></a></td></tr>
<tr><td  valign='top'><p>&nbsp;</td></tr>
<tr><td  height='15' valign='top'><p><font color='$SETFINDTITLECOLOR'><b>[기술/기능/생산직]<br></b></font></td></tr>
<tr><td  height='15' valign='top'><p>&nbsp;</td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(44)'><font color=$SETPYO_CHARCOLOR>생산관리/생산직/기능직</font><br></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(45)'><font color=$SETPYO_CHARCOLOR>기술/연구개발</font><br></a></td></tr>
</table></div>
</td>

<td width='306' height='235' valign='top' bgcolor='white'>
<div align='left'><table border='0' cellpadding='0' cellspacing='0' width='250' height='20' bgcolor='white' bordercolor='white'>
<tr><td width='255' valign='top'><p><br></td></tr>
<tr><td  valign='top'><font color='$SETFINDTITLECOLOR'><b>[컴퓨터/웹/네트워크]</b></font></td></tr>
<tr><td  valign='top'><p>&nbsp;</td></tr>
<tr><td  valign='top'><p><a href='javascript:hunt_submit(46)'><font color=$SETPYO_CHARCOLOR>웹마스터/네트워크/서버구축관리</font></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(47)'><font color=$SETPYO_CHARCOLOR>웹프로그램/컨텐츠/개발</font></a><br></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(48)'><font color=$SETPYO_CHARCOLOR>웹디자인</font><br></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(49)'><font color=$SETPYO_CHARCOLOR>데이타베이스</font><br></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(50)'><font color=$SETPYO_CHARCOLOR>웹마케팅/영업/ 정보제공/기획</font></a>&nbsp;<br></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(51)'><font color=$SETPYO_CHARCOLOR>몰마스터/쇼핑자키/샵바인더/정보검색</font><br></a></td></tr>
<tr><td  valign='top'><p>&nbsp;</td></tr>
<tr><td  height='15' valign='top'><p><font color='$SETFINDTITLECOLOR'><b>[정보통신/전산]<br></b></font></td></tr>
<tr><td  height='15' valign='top'><p>&nbsp;</td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(52)'><font color=$SETPYO_CHARCOLOR>전산/프로그래머</font></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(53)'><font color=$SETPYO_CHARCOLOR>통신기술/기술영업</font><br></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(54)'><font color=$SETPYO_CHARCOLOR>시스템분석/하드웨어/설계</font><br></a></td></tr>
<tr><td  height='15' valign='top'><p>&nbsp;</td></tr>
<tr><td  height='15' valign='top'><p><font color='$SETFINDTITLECOLOR'><b>[컴퓨터디자인]</b></font><font color='$SETFINDTITLECOLOR'><br></font></td></tr>
<tr><td  height='15' valign='top'><p>&nbsp;</td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(55)'><font color=$SETPYO_CHARCOLOR>편집디자인/MAC편집</font><br></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(56)'><font color=$SETPYO_CHARCOLOR>제품/산업디자인</font><br></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(57)'><font color=$SETPYO_CHARCOLOR>CAD/CAM</font><br></a></td></tr>
<tr><td  height='15' valign='top'><p><a href='javascript:hunt_submit(58)'><font color=$SETPYO_CHARCOLOR>캐릭터/에니메이션/그래픽디자인</font></a></td></tr>
<tr><td  height='15' valign='top'><p>&nbsp;</td></tr>
</table></div>
</td>
</tr>
</table></div>
</td>
</tr>
</table></div>
$setinfo_tail
</body>
</html> 
");
?>