<?
/*
프로그램명          새봄로(Sb-Road)
제작                   오경택
메일		             clock934@naver.com
이프로그램은 http://www.jobs21.net  에서 제작되었으며 제작자의 협의없이 재판매를 할 수 없다.
*/

echo("
<head>
<meta http-equiv='content-type' content='text/html; charset=euc-kr'>
<style type='text/css'>
BODY, table, tr, td, input, textarea, select { FONT: 9pt Gulim,굴림 }

A:link {color:black;text-decoration:none;}
            A:visited {color:gray;text-decoration:none;}
            A:active {color:black;text-decoration:none;}
            A:hover {color:green;text-decoration:none;}

TD			{FONT: 9pt Gulim,굴림}
TD .btn		{FONT-FAMILY: 굴림; FONT-SIZE: 9pt; HEIGHT: 20px}

.colorbox		{BACKGROUND-COLOR: #f5f5f5; BORDER-BOTTOM: 1px solid; BORDER-LEFT: 1px solid; BORDER-RIGHT: 1px solid; BORDER-TOP: 1px solid; FONT-FAMILY: 굴림; FONT-SIZE: 9pt}
.colorbtn		{BACKGROUND-COLOR: #f5f5f5; BORDER-BOTTOM: 1px solid; BORDER-LEFT: 1px solid; BORDER-RIGHT: 1px solid; BORDER-TOP: 1px solid; FONT-FAMILY: 굴림; FONT-SIZE: 9pt}

font			{FONT: 9pt Gulim,굴림}
font.b10		{FONT: bold 10pt Gulim,굴림}
font.b912		{FONT: bold 9pt/12pt Gulim,굴림}
font.c1		{COLOR: red; FONT: 9pt Gulim,굴림}		
font.c2		{COLOR: green; FONT: 9pt Gulim,굴림}
</style>
</head>
");
?>