<?
echo("
<html>
<head>
<title>제목없음</title>
</head>
<body bgcolor='white' text='black' link='blue' vlink='purple' alink='red'>
<table align='center' border='1' width='801'>
    <tr>
        <td width='125' height='596' valign='top'><P class=level1 style='MARGIN-LEFT: 8px'>나모 웹에디터 4 도움말</P>
<P class=desc1 style='MARGIN-LEFT: 8px'>도하고 (주)나모 
인터랙티브 홈페이지에 접속하여 사용자 등록을 한 뒤에 받으실 수 있습니다. 우선 이 도움말을 잘 살펴보거나, 많은 사용자들이 질문한 내용에 대한 
답변을 정리한 <SPAN class=src><A href='troubleshooting.htm'>문제 해결</A></SPAN>을 자세히 
 </P>
        </td>
        <td width='469' height='596' valign='top'>
		");
?>