<?
/*
프로그램명          새봄로(Sb-Road)
제작                   오경택
메일		             clock934@naver.com
이프로그램은 http://www.jobs21.net  에서 제작되었으며 제작자의 협의없이 재판매를 할 수 없다.
*/

include("inc_initarray.phtml"); //lo.phtml 로그아웃
//---------------------------------------------------------------------------
function Log_Out(){
setcookie("USER_COOKIE_HUNT","",time()+0);
setcookie("USER_COOKIE_OFFER","",time()+0);
}


Log_Out();

echo("
<META http-equiv='refresh' content='0;url=$sfile[index]'>
");
?>