<?
/*
프로그램명          새봄로(Sb-Road)
제작                   오경택
메일		             clock934@naver.com
이프로그램은 http://www.jobs21.net  에서 제작되었으며 제작자의 협의없이 재판매를 할 수 없다.
*/

//member_list_hunt_del.phtml(구직회원원관리에서 선택된 회원삭제하기)

include("inc_initarray.phtml");
//----------------------------------------------------------------------------
function Db_Connect($dbname,$id,$password,$host="localhost"){
$mysql_connect = mysql_connect($host,$id,$password) or die(mysql_error($table_connect));
$table_connect  = mysql_select_db($dbname,$mysql_connect) or die(mysql_error($table_connect));
return $table_connect;
}
//---------------------------------------------------------------------------
function Err_Msg($string){
echo("
<script>
<!--
history.go(-1);
alert('$string');
//-->
</script>
");
exit;
}
//---------------------------------------------------------------------------
$TC=Db_Connect($dfile[gugic_mem],$dbuser,$dbpass,$HOST);

if(!count($del))Err_Msg("삭제하려는 등록글을  하나 이상 선택 하십시오!");

// clock934#okt.jpg  =>     아이디#사진  [삭제작업할 DB는 구직회원DB이다]

for($i=0;$i<count($del);$i++){
$delarray=explode("#",$del[$i]);
$id=$delarray[0];		//삭제아이디
$photo=$delarray[1];	//삭제이미지(사진)

if($photo)unlink("$PHOTODIR$photo"); //사진화일이 있다면 사진화일도삭제

$QUE="	
		 DELETE FROM $table_mem[hunt] 	WHERE id = $id
		";
$RESULT=mysql_query($QUE) or die(mysql_error($table_connect));
}
echo("
<META http-equiv='refresh' content='0;url=$sfile[member_list_hunt]'>
");
?>