<?/*php_track_vars*/?> 
<?
/*
프로그램명          새봄로(Sb-Road)
제작                   오경택
메일		             clock934@naver.com
이프로그램은 http://www.jobs21.net  에서 제작되었으며 제작자의 협의없이 재판매를 할 수 없다.
*/

//member_list_hunt.phtml(구직회원관리)
include("inc_initarray.phtml");
include("html_style.phtml");

if($jsadmincookieval != "$ADMINID$ADMINPASSWORD") die("접근실패/로그기록완료!");

$line_max=$setnum_listmem;		//환경설정의 회원관리목록줄수적용
//--------------------------------------------------------------------------------
$max_line_value=$line_max; //리스트줄수     //아래에서 값이 변할수 있는 변수(max_line_value).
//----------------------------------------------------------------------------
function Db_Connect($dbname,$id,$password,$host="localhost"){
$mysql_connect = mysql_connect($host,$id,$password) or die(mysql_error($table_connect));
$table_connect  = mysql_select_db($dbname,$mysql_connect) or die(mysql_error($table_connect));
return $table_connect;
}
//---------------------------------------------------------------------------
function Err_Msg($string){
echo("
<script>
<!--
history.go(-1);
alert('$string');
//-->
</script>
");
exit;
}
//---------------------------------------------------------------------------
function Num_Str($delimiter,$str){
			$num=count(explode($delimiter,$str))-1;
			return $num;
			}
//---------------------------------------------------------------------------
$TC=Db_Connect($dfile[gugic_mem],$dbuser,$dbpass,$HOST);


if(!$tr){ //로우총갯수가 없을때만, 즉 처음만 총갯수($tr)를 구한다.

//=================================================================================
$WHERE_STR=($fstr) ? "WHERE CONCAT(id,name,birth_yyyy,tel,juso) LIKE '%$fstr%'"  :  ""; //검색을 했다면 WHERE문자열 생성
//===============================================================================

$QUE="
		SELECT count(*) FROM $table_mem[hunt] 	$WHERE_STR";

//----------------------------------------------------------------------------------

//echo($QUE);

$RESULT=mysql_query($QUE) or die(mysql_error($table_connect));
$tr=mysql_result($RESULT,0,0);
$start=1;
$page=1;	

if(!$tr)Err_Msg("구직회원없음!");
}

//----------------------------------------------------------------------------------
$total_page=ceil($tr/$max_line_value);		//분할 페이지수 
$page_rest=$tr % $max_line_value;			//분할중 나머지 rows수	

$limit_start=($max_line_value * $page)-($max_line_value); //LIMIT $limit_start, $max_line_value 
if($page==1){
					$limit_start=0;
					if($tr < $max_line_value)$max_line_value=$page_rest;
			     }
if($page==$total_page && $page_rest)$max_line_value=$page_rest;
//-----------------------------------------------------------------

$QUE="
SELECT 
id, password, name, sex, email, tel, homepage, juso_num, juso, photo, memoinfo  FROM $table_mem[hunt] $WHERE_STR ORDER BY name ASC
";
//echo($QUE);
$RESULT=mysql_query($QUE) or die(mysql_error($table_connect));
$total=mysql_num_rows($RESULT);    //전체행수

//제목부분
echo("
<HTML>
<HEAD>
<SCRIPT language='JavaScript'>
<!--
function del_submit() {		//삭제
document.form.submit();
}

function search_submit() {
//------------------------------
if(document.searchform.fstr.value == '')document.searchform.fstr.focus();
if(document.searchform.fstr.value)document.searchform.submit();
}
</SCRIPT>
</HEAD>
<BODY>
<title>구직회원관리</title>
<form name='form' method='post' action=$sfile[member_list_hunt_del]>
<div align=center>
<table border='0' cellpadding='0' cellspacing='1' width=1000 bgcolor=$setcolor_outline>
<tr>
<td width=$SET_WIDTH_HUNT_LIST height='15' valign='bottom'>
<p align='left'><font color=green>&nbsp; &nbsp; Page $total_page / Total $tr &nbsp;|&nbsp;<a href=$sfile[member_list_hunt]>구직회원목록</a>&nbsp;|&nbsp;<a href=$sfile[admin_main]>관리자메뉴</a>&nbsp;|&nbsp;<a href=$sfile[index]>시작화면</a></font> 
</td>
</tr>
</table>
</div>

<div align=center>
<table border='0' cellpadding='0' cellspacing='1' width=1000 bgcolor=$setcolor_outline>
<tr>
<td bgcolor=$SETPYO_BACKCOLOR width='100' height='20'><p align='center'><font color=$SETOUTLINE_COLOR_CHAR>ID</a></font></td>
<td bgcolor=$SETPYO_BACKCOLOR width='100' height='20'><p align='center'><font color=$SETOUTLINE_COLOR_CHAR>이름</font></td>
<td bgcolor=$SETPYO_BACKCOLOR width='30' height='25'><p align='center'><font color=$SETOUTLINE_COLOR_CHAR>성별</font></td>
<td bgcolor=$SETPYO_BACKCOLOR width='40' height='25'<p align='center'><font color=$SETOUTLINE_COLOR_CHAR>online</font></td>
<td bgcolor=$SETPYO_BACKCOLOR width='120' height='25'<p align='center'><font color=$SETOUTLINE_COLOR_CHAR>전화</font></td>
<td bgcolor=$SETPYO_BACKCOLOR width='540' height='25'<p align='center'><font color=$SETOUTLINE_COLOR_CHAR>주소</font></td>
<td bgcolor=$SETPYO_BACKCOLOR width='50' height='25'<p align='center'><font color=$SETOUTLINE_COLOR_CHAR>체킹수</font></td>
<td bgcolor=$SETPYO_BACKCOLOR width='20' height='25'<p align='center'><font color=$SETOUTLINE_COLOR_CHAR>
<a href='javascript:del_submit()'  onClick=\"return confirm('체크된 회원자료가 완전 삭제 됩니다! 정말 삭제 하시겠습니까?')\"><img src=$ICON_DEL border=0 alt='삭제'></a></font></td>
</tr>
");


//------------------------------------------------------------------------------------------------------
$inum=($page*$line_max)-$line_max;

//------------------------------------------------------------------------------------------------------
for($i=0;$i<$max_line_value;$i++){	
	mysql_data_seek($RESULT,$i);
	$da = mysql_fetch_array($RESULT);   //결과를 한줄씩 배열로 넣는다.
	$inum++;  //순번표시
	//$HOT_STR=($da[t_hot_yesno]>400)?"<img src=$ICON_HOT border=0>":""; //hot마크값 t_hot_yesno가 1이면 마크를 보임 null이면 안보임

	$NUM_sex=$da[sex];
	$NUM_memoinfo=Num_Str("#",$da[memoinfo])+1; //체크(메모)수
	$HOMEPAGESTR=($da[homepage]) ?	"<a href=$da[homepage] target=_blank><img src=$ICON_HOME border=0  alt=$da[homepage] 홈페이지방문>" : "";
	
	$CHECKVALUE=$da[id]."#".$da[photo]; //체크박스데이타	
				
//내용
$HERFMEMOSTR=(!$HTTP_COOKIE_VARS[USER_COOKIE_HUNT] && !$HTTP_COOKIE_VARS[USER_COOKIE_OFFER] && $jsadmincookieval != "$ADMINID$ADMINPASSWORD") 
? "<a href='#' onClick=\"return alert('체크기능을 사용하시려면 로그인을먼저하셔야합니다!')\"><img src=$ICON_MEMO border=0></a>"
: "<a href=\"javascript:$WINDOWSTR('db=gugic_list&tcode=$tcode&seq=$da[seq]')\">$MEMOTITLESTR</a>";

	echo("
	<tr onMouseOver=this.style.backgroundColor='e5e5e5' onMouseOut=this.style.backgroundColor='#f5f5f5' bgcolor='#f5f5f5'>
	<td height='17' valign='bottom'><p align='center'><font color=green><b>$da[id]</b></font><img src=$ICON_PV border=0 alt=암호▷$da[password]></td>
	<td height='17' valign='bottom'><p align='center'><font color=$SETPYO_CHARCOLOR>$da[name]</font></td>
	<td height='17' valign='bottom'><p align='center'><font color=$SETPYO_CHARCOLOR>$STR_sex[$NUM_sex]</font></a></td>
	<td height='17' valign='middle'><p align='left'><a href=mailto:$da[email]><img src=$ICON_EMAIL border=0 alt=메일전송></a>$HOMEPAGESTR</td>
	<td height='17' valign='bottom'><p align='center'><font color=$SETPYO_CHARCOLOR>$da[tel]</a></font>
	<td height='17' valign='bottom'><p align='left'><font color=$SETPYO_CHARCOLOR>&nbsp; $da[juso] ($da[juso_num])</font></td>
	<td height='17' valign='bottom'><p align='center'><font color=$SETPYO_CHARCOLOR>$NUM_memoinfo</td>
	<td height='17' valign='bottom'><p align='center'><input type=checkbox name=del[]	 value=$CHECKVALUE></font></td>
	</tr>
");
}//for
//----------------------------------------------------------------------------------------------

$STR="fstr=$fstr";

$move_total_page=ceil($total_page/$max_move); 
$move_rest=$total_page % $max_move;		
if($total_page < $max_move) $max_move=$total_page;  

echo("</FORM></TABLE></DIV><DIV align=center><TABLE border=0 cellpadding=0 cellspacing=0><tr><td width=$SET_WIDTH_HUNT_LIST><p align=center><br>");		

if($start > 1){	$page_prev=$start-1;		
		$start_prev=$start - $max_move; 
		print "<a href=$sfile[member_list_hunt]?$STR&page=1&start=1&tr=$tr>◁&nbsp;</a>";
		print "<a href=$sfile[member_list_hunt]?$STR&page=$page_prev&start=$start_prev&tr=$tr>☜</a>";
		}

for($i=0;$i<$max_move;$i++){	//이동단추생성	
		$page_button=$start+$i;		   
		if($page_button<=$total_page){ //최대페이지수를 초과하지 않는다면..실행
		if($page_button==$page){$color_1="<font color=green>"; $color_2="</font>";  $ahref_str1=""; $ahref_str2=""; }
		else 
		{$color_1=""; $color_2="";  $ahref_str1="<a href=$sfile[member_list_hunt]?$STR&page=$page_button&start=$start&tr=$tr>"; $ahref_str2="</a>"; }
		print "$ahref_str1 $color_1 [$page_button] $color_2 $ahref_str2";
		}
		}

if($total_page > ($start + $max_move -1)){ 		
		$page_next=$start + $max_move; 
		$start_next=$start + $max_move; 
		print "<a href=$sfile[member_list_hunt]?$STR&page=$page_next&start=$start_next&tr=$tr>☞&nbsp;</a>";
		print "<a href=$sfile[member_list_hunt]?$STR&page=$total_page&start=$total_page&tr=$tr>▷</a>";
		}
echo("
</FORM>
<div align=center>
<tr><TABLE border=0 cellpadding=0 cellspacing=1 bgcolor=$SETOUTLINE_COLOR>
<td bgcolor=$SETPYO_BACKCOLOR width=1000 height='30' valign='middle'>
<FORM name=searchform method=post action=$sfile[member_list_hunt]>
<p align='left'><input type=text name=fstr size=12><input type=button onClick='search_submit()' value=검색(모든항목)>
</FORM>
</td>
</tr>
</div>
</TABLE></DIV><BR><BR><BR>
</BODY></HTML>
");
?>