<?/*php_track_vars*/?> 
<?
/*
프로그램명          새봄로(Sb-Road)
제작                   오경택
메일		             clock934@naver.com
이프로그램은 http://www.jobs21.net  에서 제작되었으며 제작자의 협의없이 재판매를 할 수 없다.
*/

//mreg_offere.phtml 구인회원수정폼
include('inc_initarray.phtml');
include("html_style.phtml");
include($MAINMENU);


//----------------------------------------------------------------------------
function Db_Connect($dbname,$id,$password,$host="localhost"){
$mysql_connect = mysql_connect($host,$id,$password) or die(mysql_error($table_connect));
$table_connect  = mysql_select_db($dbname,$mysql_connect) or die(mysql_error($table_connect));
return $table_connect;
}
//----------------------------------------------------------------------------
function Get_Age($birth_year){             //년도로 나이구하기
$current_date=date( "Y", time() );
$AGE=$current_date-(int)$birth_year;
return $AGE;
}
//----------------------------------------------------------------------------
function Err_Msg($string){
echo("
<script>
<!--
history.go(-1);
alert('$string');
//-->
</script>
");
exit;
}
//---------------------------------------------------------------------------

$TC=Db_Connect($dfile[guin_mem],$dbuser,$dbpass,$HOST);
$QUE="
			SELECT *
			FROM $table_mem[offer] 
			WHERE id='$HTTP_COOKIE_VARS[USER_COOKIE_OFFER]'";

$RESULT= mysql_query($QUE) or die(mysql_error($TC));
$da = mysql_fetch_array($RESULT);		//결과를 한줄씩 배열로 넣는다.


//--------------------------------------------------------------------------
$dstr_class=explode("#",$da[work_class]);
for($i=1;$i<count($dstr_class)-1;$i++){
													$check_num=$mreg_offere_class_start+$dstr_class[$i];
													$script_class_str=$script_class_str."document.form.elements[".$check_num."].checked = true;  ";
													}

$dstr_area=explode("#",$da[work_area]);
for($i=1;$i<count($dstr_area)-1;$i++){
													$check_num=$mreg_offere_area_start+$dstr_area[$i];
													$script_area_str=$script_area_str."document.form.elements[".$check_num."].checked = true;  ";
													}
//-------------------------------------------------------------------------
//상장여부
$TNUM=$da[merit_yes_no];
$script_merit_yes_no="document.form.merit_yes_no.options[$TNUM].selected = true";

//회사규모
$TNUM=$da[scale];
$script_scale="document.form.scale.options[$TNUM].selected = true";

echo("
<html>
<head>
<meta http-equiv='content-type' content='text/html; charset=euc-kr'>
<title>구인회원정보수정</title>
<link href='job.css' rel='stylesheet' type='text/css'>

<SCRIPT language='JavaScript'>
<!--

function post_window(){	//우편번호입력창
window.open('$sfile[post_search_offer]','_blank','width=350,height=260,scrollbars=yes');
return true;
}

function c(){ //설정체크값로딩
$script_class_str
$script_area_str
$script_merit_yes_no
$script_scale
}



//빈칸체크------------------------------
function isFilled( elm ) {
if ( elm.value == '' || elm.value == null ) 
return false;
else
return true;
}
//숫자/문자체크-------------------------
function isInt( elm ) {
var elmstr = elm.value + '';
if ( elmstr == '' )
return false;

for ( var i=0; i<elmstr.length; i++ ) {
if ( elmstr.charAt(i) < '0' || elmstr.charAt(i) > '9' )
return false;
}
return true;
}
//-------------------------------------------


function isReady( form ) {
//-------------------------------------------
if ( isFilled(document.form.id) == false ) {
alert('구인회원 아이디를 입력하세요!');
document.form.id.focus();
return false;
}
//-------------------------------------------
if( document.form.id.value.length < 4 ){
alert('아이디는 4자이상 입니다!');
document.form.id.focus();
return false;
}
//-------------------------------------------
if( document.form.id.value.length >10 ){
alert('아이디는 10자이하 입니다!');
document.form.id.focus();
return false;
}
//-------------------------------------------
if ( isFilled(document.form.password) == false ) {
alert('구인회원 암호를 입력하세요!');
document.form.password.focus();
return false;
}
//-------------------------------------------
if( document.form.password.value.length < 4 ){
alert('암호는 4자이상 입니다!');
document.form.password.focus();
return false;
}
//-------------------------------------------
if( document.form.password.value.length  > 10 ){
alert('암호는 10자이하 입니다!');
document.form.password.focus();
return false;
}
//-------------------------------------------
if ( isFilled(document.form.repassword) == false ) {
alert('암호확인란을 입력하세요!');
document.form.repassword.focus();
return false;
}
//-------------------------------------------
if (document.form.password.value != document.form.repassword.value)
 {
alert('암호와 암호확인이 다릅니다!');
document.form.repassword.focus();
return false;
} 
//-------------------------------------------
if (isFilled(document.form.company) == false ) {
alert('회사명을 입력하세요!');
document.form.company.focus();
return false;
}
//-------------------------------------------
if ( isFilled(document.form.captain_name) == false ) {
alert('회사 대표이름을 입력하세요!');
document.form.name.focus();
return false;
}
//-------------------------------------------
if ( isFilled(document.form.email) == false ) {
alert('메일주소를 입력하세요!');
document.form.email.focus();
return false;
}
//-------------------------------------------
if ( isFilled(document.form.captain_tel) == false ) {
alert('대표전화번호를 입력하세요!');
document.form.captain_tel.focus();
return false;
}
//-------------------------------------------
if ( isFilled(document.form.juso) == false ) {
alert('회사 주소를 입력하세요!');
document.form.juso.focus();
return false;
}
//-------------------------------------------
if ( isFilled(document.form.juso_num) == false ) {
alert('회사 우편번호를 입력하세요!');
document.form.juso_num.focus();
return false;
}
//-------------------------------------------
if ( isFilled(document.form.establish_year) == false ) {
alert('회사 설립연도를 입력하세요!');
document.form.establish_year.focus();
return false;
}
//-------------------------------------------
if (document.form.establish_year.value.length < 4) {
alert('회사 설립연도는 4자리(예: 1950)로 입력하셔야 합니다.');
document.form.establish_year.focus();
return false;
}
//-------------------------------------------
if (isInt(document.form.establish_year) == false) {
alert('회사 설립연도는 4자리 숫자로 입력하셔야 합니다.');
document.form.establish_year.focus();
return false;
}

//-------------------------------------------
if ( isFilled(document.form.business_title) == false ) {
alert('회사의 주요 사업모델을 입력하세요!');
document.form.business_title.focus();
return false;
}
//-------------------------------------------
if(isInt(document.form.member) == false){
alert('직원수는 숫자로 입력하세요!');
document.form.member.focus();
return false;
}
}
//-->
</SCRIPT>
</head>

<BODY bgcolor='white' text='black' link='blue' vlink='purple' alink='red' onLoad='c()'>
<FORM name='form' onSubmit='return isReady(form)' method=post action=$sfile[mreg_offerw]>
<p align='center'><font color=$SETPYO_CHARCOLOR>『구인회원정보수정』</font><br><br> 

<div align=$setpos>
<table border='0' cellpadding='0' cellspacing='0' width='$SET_WIDTH_MREG'  height='20' bgcolor='white' bordercolor='white'>
<tr>
<td width='799' height='644'>
<div align='center'>
<table border='0' cellpadding='0' cellspacing='1' width='$SET_WIDTH_MREG' bgcolor=$setcolor_ctitle style='BORDER-BOTTOM: #006490 0px solid; BORDER-LEFT-COLOR: #006490; BORDER-LEFT-WIDTH: 0px; BORDER-RIGHT-COLOR: navy; BORDER-RIGHT-WIDTH: 0px; BORDER-TOP: #006490 0px solid'>
<tr>
<td width='$SET_WIDTH_MREG' valign='top' bgcolor='white'>

<div align=$setpos>
<table border='0' cellpadding='0' cellspacing='0' width='$SET_WIDTH_MREG' bgcolor='white' bordercolor='white'>

<tr>
<td width='86' height='26'><p align='right'>&nbsp;<font color=$SETPYO_CHARCOLOR>회원아이디<br><br></td>
<td width='104' height='26'><p align='left'>
<input type='text' tabindex=1 name='id' value='$da[id]' readonly maxlength='20' size='13' class='colorbox' index='1'>
<input type='button' tabindex=2 value='ID변경불가'></td>
<td width='84' height='26'><p align='left'>&nbsp;</td>
<td width='60' height='26'><p align='right'><font color=$SETPYO_CHARCOLOR> 회사명&nbsp;&nbsp;&nbsp;</td><td width='232' height='26'><p align='left'>
<input type='text' tabindex=7 name='company' value='$da[company]' maxlength='40' size='30' class='colorbox'>&nbsp;</td>
<td width='54' height='26'><p align='right'><font color=$SETPYO_CHARCOLOR>메일</td><td width='207' height='26'><p>
<input type='text' tabindex=10 name='email' value='$da[email]' size='28' class='colorbox'></td>
</tr>

<tr>
<td width='86'><p align='right'>&nbsp;<font color=$SETPYO_CHARCOLOR>암호</td><td width='104'><p align='left'>
<input type='password' tabindex=3 name='password' value='$da[password]' maxlength='10' size='13' class='colorbox'>&nbsp;</td>

<td width='118' colspan='2'><p align='right'>&nbsp;<font color=$SETPYO_CHARCOLOR>대표이름</td><td width='232'><p align='left'>
<input type='text' tabindex=8  name='captain_name' value='$da[captain_name]' maxlength='10' size='13' class='colorbox'></td>

<td width='54'><p align='right'><font color=$SETPYO_CHARCOLOR>대표전화</td>
<td width='207'><p>
<input type='text' tabindex=11 name='captain_tel' value='$da[captain_tel]' maxlength='14' size='28' class='colorbox'></td>
</tr>

<tr>
<td width='86'><p align='right'><font color=$SETPYO_CHARCOLOR>암호확인</td><td width='104'><p align='left'>
<input type='password' tabindex=4 name='repassword' value='$da[password]' maxlength='10' size='13' class='colorbox'></td>
<td width='118' colspan='2'><p align='right'><font color=$SETPYO_CHARCOLOR>설립연도</td>
<td width='232'><p align='left'>
<font color=$SETPYO_CHARCOLOR>
<input type='text' tabindex=8 name='establish_year' value='$da[establish_year]' maxlength='4' size='4' class='colorbox'>년 &nbsp;(4자리로 입력) 예: 1950</td>
<td width='54'><p align='right'>&nbsp;<font color=$SETPYO_CHARCOLOR>팩스</td>
<td width='207'><p>
<input type='text' tabindex=12 name='fax' value='$da[fax]' maxlength='14' size='28' class='colorbox'></td>
</tr>

<tr>
<td width='86'><p align='right'><font color=$SETPYO_CHARCOLOR>회사주소</td><td width='104'><p>
<font color=$SETPYO_CHARCOLOR>
<input type='button' tabindex=5 value='주소자동입력' onClick='post_window()'></td>
<td width='118' colspan='2'><p align='right'><font color=$SETPYO_CHARCOLOR>회사주소</td>
<td width='495' colspan='3'><p align='left'>
<input type='text' tabindex=13 name='juso' value='$da[juso]'size='62' class='colorbox'> 
<input type='text' tabindex=14 name='juso_num' value='$da[juso_num]'maxlength='7' size='11' class='colorbox'></td>
</tr>

<tr>
<td width='86'><p align='right'><font color=$SETPYO_CHARCOLOR>홈페이지</td><td width='700' colspan='6'><p align='left'>
<input type='text' tabindex=6 name='homepage' value='$da[homepage]' maxlength='50' size='29' class='colorbox'> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</td>
</tr>

<tr>
<td width='86'><p align='right'><font color=$SETPYO_CHARCOLOR>상장여부</td><td width='700' colspan='6'><p align='left'>
<font color=$SETPYO_CHARCOLOR>
<select name='merit_yes_no' class='colorbox'>
                                    <option value='0'>비상장</option>
                                    <option value='1'>상장</option>
									</select> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


회사규모
<select name='scale' class='colorbox'>
                                    <option value='0'>대기업</option>
                                    <option value='1' selected >중소기업</option>
									<option value='2'>밴처기업</option>
									<option value='3'>자영업</option>
									<option value='4'>프리랜서</option>
									</select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

직원수
<input type='text'  name='member' value='$da[member]' maxlength='10' size='5' class='colorbox'>명 (숫자로입력)
</td>
</tr>

<tr>
<td width='86'><p align='right'><font color=$SETPYO_CHARCOLOR>회사자본금</td><td width='700' colspan='6'><p align='left'><font color=$SETPYO_CHARCOLOR>
<input type='text' name='funds' value='$da[funds]' maxlength='10' size='10' class='colorbox'>(예:7억7천만)
</td>
</tr>

<tr>
<td width='86'><p align='right'><font color=$SETPYO_CHARCOLOR>주요사업모델</td><td width='700' colspan='6'><p align='left'>
<font color=$SETPYO_CHARCOLOR>
<input type='text' name='business_title' value='$da[business_title]' maxlength='50' size='50' class='colorbox'>
(예:네트웍설비구축/유지보수)
</td>
</tr>

<tr>
<td width='86'><p align='right'><font color=$SETPYO_CHARCOLOR>회사소개</td><td width='700' colspan='6'><p align='left'>
<textarea name='content' rows='15' cols='100' class='colorbox'>$da[content]</textarea></td>
</tr>

<tr><td width='86'><p align='right'>&nbsp;</td>
<td width='700' colspan='6'><p align='left'></td></tr>
<tr><td width='86'><p align='right'>&nbsp;</td>
<td width='700' colspan='6'><p align='left'><font color=$SETPYO_CHARCOLOR>구인리스트에 등록할 때 나타나는 모집요강 입력란 입니다. 미리 입력해 두면 편리합니다!</td></tr>

<tr><td width='86'><p align='right'><font color=$SETPYO_CHARCOLOR>모집요강</td>
<td width='700' colspan='6'><p align='left'>
<textarea name='paper' rows='15' cols='100' class='colorbox'>$da[paper]</textarea></td></tr>



</table></div>
</td>
</tr>
</table></div>

<br><br>
 <font color='green'><b>[구인업종선택] </b></font><font color=$SETPYO_CHARCOLOR>☜구인업종분류는 5개까지 선택이 가능합니다. 이자료는 구인리스트에 등록시 근무업종 선택란의 기본값으로 사용됩니다.<br> 
<div align=$setpos><table border='0' cellpadding='0' cellspacing='1' width='$SET_WIDTH_MREG' bgcolor=$setcolor_outline style='BORDER-BOTTOM: #006490 0px solid; BORDER-LEFT-COLOR: #006490; BORDER-LEFT-WIDTH: 0px; BORDER-RIGHT-COLOR: navy; BORDER-RIGHT-WIDTH: 0px; BORDER-TOP: #006490 0px solid'>

<tr>
<td width='256' valign='top' bgcolor='white'>

<div align=$setpos>
<table border='0' cellpadding='0' cellspacing='0' width='250' height='20' bgcolor='white' bordercolor='white'>

<tr><td width='255' valign='top'><p>&nbsp;</td></tr>
<tr><td width='255' valign='top'><p><font color='green'><b>[업종별]</b></font></td></tr>
<tr><td width='255' valign='top'><p>&nbsp;</td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='0'><font color=$SETPYO_CHARCOLOR>건설/토목/건축/조경<br></td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='1'><font color=$SETPYO_CHARCOLOR>광고(기획/홍보/영업/제작)</td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='2'><font color=$SETPYO_CHARCOLOR>교육/강사/학원</td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='3'><font color=$SETPYO_CHARCOLOR>농업/수산업/축산업/광업</td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='4'><font color=$SETPYO_CHARCOLOR>기계/자동차/금속</td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='5'><font color=$SETPYO_CHARCOLOR>관광/호텔/여행/항공<br></td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='6'><font color=$SETPYO_CHARCOLOR>금융기관(은행/금고/증권/보험)<br></td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='7'><font color=$SETPYO_CHARCOLOR>건강/병원/의약/화장품<br></td></tr>
<tr><td width='255' valign='top'><p><input type='checkbox' name='work_class[]' value='8'><font color=$SETPYO_CHARCOLOR>공공기관/공사/공공서비스/협회</td></tr>
<tr><td width='255' valign='top'><p><input type='checkbox' name='work_class[]' value='9'><font color=$SETPYO_CHARCOLOR>방송/언론<br></td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='10'><font color=$SETPYO_CHARCOLOR>출판/인쇄/편집</td></tr>
<tr><td width='255' valign='top'><p><input type='checkbox' name='work_class[]' value='11'><font color=$SETPYO_CHARCOLOR>목재/제지</td></tr>
<tr><td width='255' valign='top'><p><input type='checkbox' name='work_class[]' value='12'>유<font color=$SETPYO_CHARCOLOR>통/운송/음식료</td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='13'><font color=$SETPYO_CHARCOLOR>석유/화학/에너지<br></td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='14'><font color=$SETPYO_CHARCOLOR>섬유/의류/패션&nbsp; <br></td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='15'><font color=$SETPYO_CHARCOLOR>전기/전자/컴퓨터<br></td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='16'><font color=$SETPYO_CHARCOLOR>용역/기타서비스<br></td></tr>
<tr><td width='255' valign='top'><p>&nbsp;</td> </tr>
<tr><td width='255' valign='top'><p><font color='green'><b>[기타]</b></font><font color='green'><br></font></td></tr>
<tr><td width='255' valign='top'><p>&nbsp;</td></tr>
<tr><td width='255' valign='top'><p><input type='checkbox' name='work_class[]' value='17'><font color=$SETPYO_CHARCOLOR>임원</td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='18'><font color=$SETPYO_CHARCOLOR>아르바이트<br></td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='19'><font color=$SETPYO_CHARCOLOR>병역특례<br></td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='20'><font color=$SETPYO_CHARCOLOR>프리랜서<br></td></tr>
<tr><td width='255' valign='top'><p><input type='checkbox' name='work_class[]' value='21'><font color=$SETPYO_CHARCOLOR>자원봉사<br></td></tr>
<tr><td width='255' valign='top'><p><input type='checkbox' name='work_class[]' value='22'><font color=$SETPYO_CHARCOLOR>장애인</td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='23'><font color=$SETPYO_CHARCOLOR>고령인<br></td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='24'><font color=$SETPYO_CHARCOLOR>노무직<br></td></tr>
<tr><td width='255' valign='top'><p>&nbsp;</td></tr>
</table></div>

<p>&nbsp;</td>
<td width='234' valign='top' bgcolor='white'>
<div align='center'>
<table border='0' cellpadding='0' cellspacing='0' width='250' height='20' bgcolor='white' bordercolor='white'>
<tr>
<td width='236' valign='top'><p>&nbsp;</td></tr>
<tr><td width='236' valign='top'><p><font color='green'><b>[사무관리직]</b></font></td></tr>
<tr><td width='236' valign='top'><p>&nbsp;</td></tr>
<tr><td width='236' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='25'><font color=$SETPYO_CHARCOLOR>경리/회계/재무<br></td></tr>
<tr><td width='236' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='26'><font color=$SETPYO_CHARCOLOR>마케팅/영업(국내)</td></tr>
<tr><td width='236' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='27'><font color=$SETPYO_CHARCOLOR>무역/영업(해외)&nbsp;<br></td></tr>
<tr><td width='236' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='28'><font color=$SETPYO_CHARCOLOR>사무직(기획/총무/인사/자재/비서)<br></td></tr>
<tr><td width='236' height='14' valign='top'><p>&nbsp;</td></tr>
<tr><td width='236' valign='top'><p><font color='green'><b>[전문직]</b></font><font color='green'><br></font></td></tr>
<tr><td width='236' valign='top'><p>&nbsp;</td></tr>
<tr><td width='236' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='29'><font color=$SETPYO_CHARCOLOR>법률/특허<br></td></tr>
<tr><td width='236' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='30'><font color=$SETPYO_CHARCOLOR>증권</td></tr>
<tr><td width='236' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='31'><font color=$SETPYO_CHARCOLOR>번역/통역<br></td></tr>
<tr><td width='236' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='32'><font color=$SETPYO_CHARCOLOR>세무/회계<br></td></tr>
<tr><td width='236' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='33'><font color=$SETPYO_CHARCOLOR>공인중개사/부동산<br></td></tr>
<tr><td width='236' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='34'><font color=$SETPYO_CHARCOLOR>통계/수리<br></td></tr>
<tr><td width='236' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='35'><font color=$SETPYO_CHARCOLOR>감정평가<br></td></tr>
<tr><td width='236' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='36'><font color=$SETPYO_CHARCOLOR>경매관리<br></td></tr>
<tr><td width='236' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='37'><font color=$SETPYO_CHARCOLOR>경영지도/경영분석</td></tr>
<tr><td width='236' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='38'><font color=$SETPYO_CHARCOLOR>인테리어/실내디자인<br></td></tr>
<tr><td width='236' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='39'><font color=$SETPYO_CHARCOLOR>의상/패션디자인/코디네이터<br></td></tr>
<tr><td width='236' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='40'><font color=$SETPYO_CHARCOLOR>이벤트/레크레이션<br></td></tr>
<tr><td width='236' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='41'><font color=$SETPYO_CHARCOLOR>비디오촬영/카메라<br></td></tr>
<tr><td width='236' valign='top'><p><input type='checkbox' name='work_class[]' value='42'><font color=$SETPYO_CHARCOLOR>미용</td></tr>
<tr><td width='236' valign='top'><p><input type='checkbox' name='work_class[]' value='43'><font color=$SETPYO_CHARCOLOR>서적/소설/시/만화/작가<br></td></tr>
<tr><td width='236' valign='top'><p>&nbsp;</td></tr>
<tr><td width='236' height='15' valign='top'><p><font color='green'><b>[기술/기능/생산직]<br></b></font></td></tr>
<tr><td width='236' height='15' valign='top'><p>&nbsp;</td></tr>
<tr><td width='236' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='44'><font color=$SETPYO_CHARCOLOR>생산관리/생산직/기능직<br></td></tr>
<tr><td width='236' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='45'><font color=$SETPYO_CHARCOLOR>기술/연구개발<br></td></tr>
</table></div>
</td>

<td width='306' valign='top' bgcolor='white'>
<div align='left'>
<table border='0' cellpadding='0' cellspacing='0' width='250' height='20' bgcolor='white' bordercolor='white'>
<tr><td width='255' valign='top'><p><br></td></tr>
<tr><td width='255' valign='top'><p><font color='green'><b>[컴퓨터/웹/네트워크]</b></font></td></tr>
<tr><td width='255' valign='top'><p>&nbsp;</td></tr>
<tr><td width='255' valign='top'><p><input type='checkbox' name='work_class[]' value='46'><font color=$SETPYO_CHARCOLOR>웹마스터/네트워크/서버구축관리</td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='47'><font color=$SETPYO_CHARCOLOR>웹프로그램/컨텐츠/개발<br></td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='48'><font color=$SETPYO_CHARCOLOR>웹디자인<br></td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='49'><font color=$SETPYO_CHARCOLOR>데이타베이스<br></td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='50'><font color=$SETPYO_CHARCOLOR>웹마케팅/영업/정보제공/기획&nbsp;<br></td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='51'><font color=$SETPYO_CHARCOLOR>몰마스터/쇼핑자키/샵바인더/정보검색<br></td></tr>
<tr><td width='255' valign='top'><p>&nbsp;</td></tr>
<tr><td width='255' height='15' valign='top'><p><font color='green'><b>[정보통신/전산]<br></b></font></td></tr>
<tr><td width='255' height='15' valign='top'><p>&nbsp;</td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='52'><font color=$SETPYO_CHARCOLOR>전산/프로그래머</td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='53'><font color=$SETPYO_CHARCOLOR>통신기술/기술영업<br></td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='54'><font color=$SETPYO_CHARCOLOR>시스템분석/하드웨어/설계<br></td></tr>
<tr><td width='255' height='15' valign='top'><p>&nbsp;</td></tr>
<tr><td width='255' height='15' valign='top'><p><font color='green'><b>[컴퓨터디자인]</b></font><font color='green'><br></font></td></tr>
<tr><td width='255' height='15' valign='top'><p>&nbsp;</td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='55'><font color=$SETPYO_CHARCOLOR>편집디자인/MAC편집<br></td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='56'><font color=$SETPYO_CHARCOLOR>제품/산업디자인<br></td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='57'><font color=$SETPYO_CHARCOLOR>CAD/CAM<br></td></tr>
<tr><td width='255' height='15' valign='top'><p><input type='checkbox' name='work_class[]' value='58'><font color=$SETPYO_CHARCOLOR>캐릭터/에니메이션/그래픽디자인</td></tr>
<tr><td width='255' height='15' valign='top'><p>&nbsp;</td></tr>
</table></div></td>
</tr>

<tr>
<td width='$SET_WIDTH_MREG' valign='top' colspan='3' bgcolor='white'><p><br> <br> <font color='green'><b>[근무희망지역선택] </b></font>
<font color=$SETPYO_CHARCOLOR>☜근무희망지역은 4개까지 선택이 가능합니다. 이자료는 구인리스트에 등록시 근무지역 선택란의 기본값으로 사용됩니다.
<div align='center'>
<table border='0' cellpadding='0' cellspacing='1' width='750' bgcolor=$setcolor_outline style='BORDER-BOTTOM: #006490 0px solid; BORDER-LEFT-COLOR: #006490; BORDER-LEFT-WIDTH: 0px; BORDER-RIGHT-COLOR: navy; BORDER-RIGHT-WIDTH: 0px; BORDER-TOP: #006490 0px solid'>
<tr>

<td width='733' bgcolor='white'><p><font color=$SETPYO_CHARCOLOR>
<input type='checkbox' name='work_area[]' value='0'>서울 &nbsp;
<input type='checkbox' name='work_area[]' value='1'>경기 &nbsp;
<input type='checkbox' name='work_area[]' value='2'>인천 &nbsp;
<input type='checkbox' name='work_area[]' value='3'>강원 
<input type='checkbox' name='work_area[]' value='4'>대전 &nbsp;
<input type='checkbox' name='work_area[]' value='5'>충남 &nbsp;
<input type='checkbox' name='work_area[]' value='6'>충북 &nbsp;
<input type='checkbox' name='work_area[]' value='7'>전북 &nbsp;
<input type='checkbox' name='work_area[]' value='8'>전남 &nbsp;
<input type='checkbox' name='work_area[]' value='9'>광주 &nbsp;
<input type='checkbox' name='work_area[]' value='10'>경북 &nbsp;
<input type='checkbox' name='work_area[]' value='11'>경남 
</td></tr>

<tr>
<td width='733' bgcolor='white'><p><font color=$SETPYO_CHARCOLOR>
<input type='checkbox' name='work_area[]' value='12'>대구 &nbsp;
<input type='checkbox' name='work_area[]' value='13'>울산 &nbsp;
<input type='checkbox' name='work_area[]' value='14'>부산 &nbsp;
<input type='checkbox' name='work_area[]' value='15'>제주 
<input type='checkbox' name='work_area[]' value='16'>아시아 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<input type='checkbox' name='work_area[]' value='17'>아프리카 &nbsp;
<input type='checkbox' name='work_area[]' value='18'>중남미 &nbsp;
<input type='checkbox' name='work_area[]' value='19'>오세아니아 &nbsp;&nbsp;
<input type='checkbox' name='work_area[]' value='20'>유럽 &nbsp;
<input type='checkbox' name='work_area[]' value='21'>북미&nbsp;
</td>
</tr>
</table></div>

<p align='center'><input type='submit' value='구인회원정보수정'>
<br><br>
</td>
</table></div>
</td>
</tr>
</table></div>
<INPUT type=hidden name=edit_mode value='EDIT'>
</form>
$setinfo_tail
</body>
</html> 
");
?>