<?
/*
프로그램명          새봄로(Sb-Road)
제작                   오경택
메일		             clock934@naver.com
이프로그램은 http://www.jobs21.net  에서 제작되었으며 제작자의 협의없이 재판매를 할 수 없다.
*/

//tmp_huntw.phtml(입사희망서를 JOTMP.offer_temp_table 에 저장)
include("inc_initarray.phtml");

//----------------------------------------------------------------------------
function Db_Connect($dbname,$id,$password,$host="localhost"){
$mysql_connect = mysql_connect($host,$id,$password) or die(mysql_error($table_connect));
$table_connect  = mysql_select_db($dbname,$mysql_connect) or die(mysql_error($table_connect));
return $table_connect;
}
//---------------------------------------------------------------------------
function Err_Msg($string){
echo("
<script>
<!--
history.go(-1);
alert('$string');
//-->
</script>
");
exit;
}
//--------------------------------------------------------------------------
function Self_Close(){
echo("
<script>
<!--
self.close();
//-->
</script>
");
exit;
}
//----------------------------------------------------------------------------------------------------
function email($to,$subject, $msg,$from,$MAILER="/usr/sbin/sendmail -t  -ba") 
{ 
$header = sprintf("From: %s\nTo: %s\nSubject: %s\n",$from,$to,$subject); 
$fp =popen($MAILER,"w"); 
fputs($fp,$header); 
fputs($fp,"$msg\n"); 
pclose($fp); 
} 

//---------------------------------------------------------------------------
$TC=Db_Connect($dfile[guin_tmp],$dbuser,$dbpass,$HOST);

$QUE="
		INSERT INTO $table_tmp[offer]	VALUES('','$id_mine','$id_fk_huntmem', '$title', '$content', NOW())
		";

//echo $QUE; exit;
$RESULT=mysql_query($QUE) or die(mysql_error($table_connect));

//메일전송--------------------------------------------------------------------
$msg="
『 $title 』\n
$content\n
";
email($toemail,$title,$msg,$email);
Self_Close();
?>