<?
/*
프로그램명          새봄로(Sb-Road)
제작                   오경택
메일		             clock934@naver.com
이프로그램은 http://www.jobs21.net  에서 제작되었으며 제작자의 협의없이 재판매를 할 수 없다.
*/

//tmp_list_view.phtml(수신메세지리스트내용보기)
include("inc_initarray.phtml");
include("html_style.phtml");
include($MAINMENU);
//--------------------------------------------------------------------------------
$max_line_value=$line_max; //리스트줄수     //아래에서 값이 변할수 있는 변수(max_line_value).
//----------------------------------------------------------------------------
function Db_Connect($dbname,$id,$password,$host="localhost"){
$mysql_connect = mysql_connect($host,$id,$password) or die(mysql_error($table_connect));
$table_connect  = mysql_select_db($dbname,$mysql_connect) or die(mysql_error($table_connect));
return $table_connect;
}
//---------------------------------------------------------------------------
function Err_Msg($string){
echo("
<script>
<!--
history.go(-1);
alert('$string');
//-->
</script>
");
exit;
}

$TC=Db_Connect($dfile[$db],$dbuser,$dbpass,$HOST);


//구직과 구인을 구별하여 쿼리를 적용한다.
$QUE=($db == "gugic_tmp")?"SELECT seq, id_fk_offermem, name, email, tel , title , content, date  FROM $table_tmp[$table] WHERE 	id_mine = '$id_mine'  ORDER BY seq DESC"
								    :"SELECT seq, id_fk_huntmem,title,content  FROM $table_tmp[$table] WHERE id_mine = '$id_mine'  ORDER BY seq DESC";
$RESULT=mysql_query($QUE) or die(mysql_error($table_connect));
$da = mysql_fetch_array($RESULT);   //결과를 한줄씩 배열로 넣는다.

//----------------------------------------------------------
//내용
$da[content]=nl2br($da[content]); //\n을 -> <br>로
$da[content]=eregi_replace(" ","&nbsp;",$da[content]); //space를 -> &nbsp;로
//----------------------------------------------------------

$WINDOWWIDTH=$SET_WIDTH_OFFER_VIEW_CO+50;		//회사상세정보윈도우창

echo("
<HTML>
<HEAD>
<SCRIPT>
	
	function window_view(str){ //설정체크값로딩
	open(str,'new_win','width=$WINDOWWIDTH,height=500,scrollbars=yes,resizable=yes');
	}

</SCRIPT>
</HEAD>
<BODY>
<title>구직등록자검색</title>
<br>
<div align=$setpos>
<table border='0' cellpadding='0' cellspacing='1' width=800 bgcolor='$setcolor_outline'>
<tr>
<td width=$SET_WIDTH_HUNT_LIST height='15' valign='bottom'>
<p align='left'><font color=$SETSUBJECT_CHARCOLOR>『수신메세지 >> 자세히보기』</font></td>
</tr>
</table>
</div>

<div align=$setpos>
<table border='0' cellpadding='0' cellspacing='1' width=800 bgcolor=$setcolor_outline>
<tr>
<td bgcolor=$SETPYO_BACKCOLOR width='100' height='20'><p align='center'><font color=$SETOUTLINE_COLOR_CHAR>당당자이름</font></td>
<td bgcolor=$SETPYO_BACKCOLOR width='130' height='25'<p align='center'><font color=$SETOUTLINE_COLOR_CHAR>보낸시각</font></td>
<td bgcolor=$SETPYO_BACKCOLOR width='100' height='25'<p align='center'><font color=$SETOUTLINE_COLOR_CHAR>담당자전화</font></td>
<td bgcolor=$SETPYO_BACKCOLOR width='470' height='25'<p align='center'><font color=$SETOUTLINE_COLOR_CHAR>제목</font></td>
</td>
</tr>

<tr>
<td bgcolor=white height='17' valign='bottom'><p align='right'><font color=$SETPYO_CHARCOLOR>$da[name]&nbsp;&nbsp;<a href=mailto:$da[email]><img src=$ICON_EMAIL border=0></font></td>
<td bgcolor=white height='17' valign='bottom'><p align='center'><font color=green>$da[date]</font></td>
<td bgcolor=white height='17' valign='bottom'><p align='right'><font color=$SETPYO_CHARCOLOR>$da[tel] &nbsp;</font></a></td>
<td bgcolor=white height='17' valign='bottom'><p align='left'><font color=$SETPYO_CHARCOLOR>&nbsp;$da[title]</a></font></td>
</tr>
</FORM>
</TABLE>
</DIV>

<br>
<div align=$setpos>
<table border='0' cellpadding='0' cellspacing='1' width=800 bgcolor=white>
<tr>
<td width=800 height='17' valign='bottom'><p align='right'>
<a href=\"javascript:history.back()\"><font color=$SETPYO_CHARCOLOR><u>/목록으로 </u></font></a> &nbsp;
<a href=\"javascript:window_view('$sfile[tmp_list_view_co]?fk=$da[id_fk_offermem]')\"><font color=$SETPYO_CHARCOLOR><u>/회사상세정보</u></font></a>
</td>
</tr>
</FORM>
</TABLE>
</DIV>


<DIV align=$setpos>
<TABLE border=0 cellpadding=0 cellspacing=0><tr><td width=$SET_WIDTH_HUNT_LIST><p align=center><br>
<tr>
<TABLE border=0 cellpadding=0 cellspacing=1 bgcolor=$setcolor_outline>
<td bgcolor=$SETPYO_BACKCOLOR width=800 height='30' valign='middle'><br><font color=$SETPYO_CHARCOLOR>$da[content]</font></td>
</tr>
</TABLE>
</DIV>
$setinfo_tail
</BODY>
</HTML>
");
?>